### ISSUE TITLE
About Factorial.java

### ISSUE THREAD

**Issue by Learn-git-SAM** [REC-SAM/Programs#3]
Fix the following things
- [ ] Add `static` to fact().
- [ ] Write the base condition for the fact()

**Comment by REC-SAM** [comment]
Thanks for the help.

> Fix the following things
> 
> * [x]  Add `static` to fact().
> * [ ]  Write the base condition for the fact()

**Comment by REC-SAM** [comment]
Can you help me with base condition ?

**Comment by Learn-git-SAM** [comment]
Ok, make me a collaborator

**Comment by Learn-git-SAM** [comment]
Fixed the base condition
